def get_film_lista() -> list:
    filmek = []
    filmek.append('Te rongyos élet')
    filmek.append('Bölcsőd lesz a koporsód')
    filmek.append('Állj vagy jövök')
    filmek.append('Egértanya')
    filmek.append('Mérges Pókok')
    filmek.append('A sárkány csókja')
    filmek.append('Mackótestvér')
    filmek.append('A Kör')
    filmek.append('Csajok a csúcson')
    filmek.append('Ellenséges terület')
    filmek.append('Jonny English')
    filmek.append('Golyóálló szerzetes')
    filmek.append('Macskafogó')
    filmek.append('Randiguru')
    filmek.append('Apám beájulna')
    filmek.append('Gagyimami')
    filmek.append('Túl közeli rokon')
    filmek.append('Blöff')
    filmek.append('Apja lánya')
    filmek.append('Az invázió')
    filmek.append('Két hét múlva örökké')
    filmek.append('Az utolsó gyémántrablás')
    filmek.append('Harry Potter a tűz serlege')
    filmek.append('Macskanő')
    filmek.append('Robotok')
    filmek.append('Az új fiú')
    filmek.append('Apafej')
    filmek.append('Sátánka')
    filmek.append('Csak szex és más semmi')
    filmek.append('Meseautó')
    filmek.append('Fegyverek szava')
    filmek.append('Segítség hal lettem')
    filmek.append('A gyönyör játékai')
    filmek.append('Rubint Réka')
    filmek.append('Eldorado')
    filmek.append('Veszélyes elemek')
    filmek.append('Madagaskar')
    filmek.append('Ellenség a kapuknál')
    filmek.append('Szex lecke')
    filmek.append('Feketék fehéren')
    filmek.append('A rettegés arénája')
    filmek.append('Harry Potter és a titkok kamrája')
    filmek.append('A Part')
    filmek.append('Brian élete')
    filmek.append('Üvegtigris')
    filmek.append('Magyar vándor')
    filmek.append('A fenegyerek')
    filmek.append('A jövő kezdete')
    filmek.append('Arthur király')
    filmek.append('Katonák voltunk')
    filmek.append('Atlantis')
    filmek.append('Trainspotting')
    filmek.append('Hulk')
    filmek.append('A keménykötésűek')
    filmek.append('Gyilkos álmok')
    filmek.append('Pánikszoba')
    filmek.append('Fekete lovag')
    filmek.append('Kárhozottak királynője')
    filmek.append('Milliókért a pokolba')
    filmek.append('Beépített szépség')
    filmek.append('Végső állomás')
    filmek.append('Kincses bolygó')
    filmek.append('A Tökös a Török az őr meg a nő')
    filmek.append('Flört a fellegekben')
    filmek.append('Bérgyilkos a szomszédom')
    filmek.append('Hölgyválasz')
    filmek.append('A csaj nem jár egyedül')
    filmek.append('Harry Potter és az azkabani fogoly')
    filmek.append('Háború a Földön')
    filmek.append('Egy szoknya egy nadrág')
    filmek.append('Kisérlet')
    filmek.append('Trója')
    filmek.append('Neveletlen hercegnő')
    filmek.append('Halálnak halála')
    filmek.append('Mindenható')
    filmek.append('Némó nyomában')
    filmek.append('Péntek esti gáz')
    filmek.append('Nő a baj')
    filmek.append('Macskajaj')
    filmek.append('A falu')
    filmek.append('Shrek')
    filmek.append('Harry Potter és a bölcsek köve')
    filmek.append('Az utolsó szamuráj')
    filmek.append('Bújócska')
    filmek.append('Mi kell a nőnek')
    filmek.append('Sárkányszív')
    filmek.append('Jég és föld között')
    filmek.append('Vejedre ütök')
    filmek.append('Shaft')
    filmek.append('Halott madarak')
    filmek.append('Pofa be')
    filmek.append('A sólyom végveszélyben')
    filmek.append('Másvilág')
    filmek.append('Szüzet szüntess')
    filmek.append('Az átok')
    filmek.append('Jégkorszak')
    filmek.append('Hannibal')
    filmek.append('Két testben elszabadulva')
    filmek.append('Édes kis semmiség')
    filmek.append('Pelenkás bajkeverő')
    return filmek